version: '3.9'

# Services
services:
  # Server service
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"

  # Client service
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - server
